spring:
  application:
    name: cloud-grpc-server
  sleuth:
    sampler:
      percentage: 1
  cloud:
    consul:
      host: 192.168.1.252
      port: 8500
server:
  port: 0
grpc:
  server:
    port: 0
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

